In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from PyNomaly import loop
import matplotlib.pyplot as plt
import string
import random

In [2]:
columns = {"letter": "capital letter (26 values from A to Z)", "x-box": "horizontal position of box(integer)",
           "y-box": "vertical position of box(integer)", "width": "width	width of box(integer)",
           "high": "height of box(integer)", "onpix": "onpix	total", "x-bar": "mean x of on pixels in box(integer)",
           "y-bar": "mean y of on pixels in box(integer)", "x2bar": "mean x variance(integer)", "y2bar": "mean y variance (integer)",
           "xybar": "mean x y correlation	(integer)", "x2ybr": "mean of x * x * y	(integer)", "xy2br": "mean of x * y * y (integer)",
           "x-ege": "mean edge count left to right (integer)", "xegvy": "correlation of x-ege with y (integer)",
           "y-ege": "mean edge count bottom to top	(integer)", "yegvx": "correlation of y-ege with x (integer)"}


path = Path("../../Data/letter-recognition.data")

# get the whole alphabet
alphabet = list(string.ascii_uppercase)

# read the data
df_letters = pd.read_csv(path, names=list(columns.keys()))

dataframes = dict()

In [3]:
df_letters

,letter,x-box,y-box,width,high,onpix,x-bar,y-bar,x2bar,y2bar,xybar,x2ybr,xy2br,x-ege,xegvy,y-ege,yegvx
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [5]:
sum = 0

# fill dict with letter as key and filtered dataframe per letter and get the number of all entries
for letter in alphabet:
    df = df_letters.loc[(df_letters.letter == letter), :]
    df = df.drop('letter', axis=1, inplace=False)
    sum += len(df.index)
    print(letter, len(df.index))
    dataframes[letter] = df

A 789
B 766
C 736
D 805
E 768
F 775
G 773
H 734
I 755
J 747
K 739
L 761
M 792
N 783
O 753
P 803
Q 783
R 758
S 748
T 796
U 813
V 764
W 752
X 787
Y 786
Z 734

In [4]:
2000/16

125.0

In [23]:
columns = list(df_letters.columns)

decision = [True, False]

for letter, dataframe in dataframes.items():
    indexes = list(dataframe.index)
    amount = len(dataframe.index)/16
    st_div = pd.DataFrame(dataframe.std())
    st_div.rename(columns = {"0":'Std'}, inplace = True)
    st_div["std*0.5"] = st_div["Std"] * 0.5
    
    for column in columns:
        addition = random.sample(decision, 1)
        indexes_to_use = random.sample(indexes, int(amount))
        print(dataframe.loc[indexes_to_use, column])
        print(addition)
        if addition:
            dataframe.loc[indexes_to_use, column] = dataframe.loc[indexes_to_use, column] + st_div.loc[column, "std*0.5"]
        else:
            dataframe.loc[indexes_to_use, column] = dataframe.loc[indexes_to_use, column] - st_div.loc[column, "std*0.5"]
        print(dataframe.loc[indexes_to_use, column])
        indexes = [ele for ele in indexes if ele not in indexes_to_use]
    print(dataframe)

KeyError: 'Std'

In [6]:
df_letters.columns

Index(['letter', 'x-box', 'y-box', 'width', 'high', 'onpix', 'x-bar', 'y-bar',
       'x2bar', 'y2bar', 'xybar', 'x2ybr', 'xy2br', 'x-ege', 'xegvy', 'y-ege',
       'yegvx'],
      dtype='object')

In [21]:
list1 = range(1, 20)
list2 = range(10,20)

list3 = [ele for ele in list1 if ele not in list2]

In [22]:
list3

[1, 2, 3, 4, 5, 6, 7, 8, 9]